known_skills = [
    "ece", "cse" ,"it", "ee", "electronics & communication engineering", "engineering", "engineer", "computer", "computer science engineering", 
    "electrical engineering", "information technology", "ce", "me", "mechanical engineering", "Bachelor in technology", "B.Tech", 
    "B.Sc", 
  "React Native",
  "React.js",
  "Next.js",
  "Node.js",
  "Express.js",
  "JavaScript",
  "TypeScript",
  "MongoDB",
  "SQL",
  "HTML",
  "CSS",
  "React Query",
  "Java",
  "Python",
  "C++",
  "Excel",
  "PowerPoint",
  "Word",
  "Google Suite",
  "Public Speaking",
  "Active Listening",
  "Professional Writing",
  "Proposal Writing",
  "Virtual Presentation",
  "English",
  "Hindi",
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "MUI",
  "Chakra UI",
  "Bulma",
  "Sass",
  "SCSS",
  "Styled Components",
  "Emotion",
  "React.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Preact",
  "jQuery",
  "Redux",
  "React Context API",
  "Recoil",
  "MobX",
  "Zustand",
  "Redux Toolkit",
  "Vuex",
  "Pinia",
  "React Router",
  "React Query",
  "React Hook Form",
  "Formik",
  "React Testing Library",
  "Next.js",
  "npm",
  "yarn",
  "pnpm",
  "Webpack",
  "Vite",
  "Parcel",
  "Babel",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Puppeteer",
  "Playwright",
  "Enzyme",
  "Gulp",
  "Grunt",
  "Git",
  "GitHub Actions",
  "Netlify",
  "Vercel",
  "REST API",
  "GraphQL",
  "Axios",
  "Fetch API",
  "WebSockets",
  "Apollo Client",
  "Ant Design",
  "React Bootstrap",
  "Fluent UI",
  "PrimeReact",
  "Carbon Design System",
  "React Native",
  "Expo",
  "Ionic",
  "Flutter",
  "PWA",
  "Figma",
  "Adobe XD",
  "Sketch",
  "InVision",
  "Framer",
  "Zeplin",
  "Storybook",
  "ESLint",
  "Prettier",
  "Husky",
  "Lint-staged",
  "Browserslist",
  "Lighthouse",
  "Java",
  "Python",
  "Node.js",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "C#",
  "Scala",
  "Kotlin",
  "Express.js",
  "Spring Boot",
  "Django",
  "Flask",
  "FastAPI",
  "NestJS",
  "Ruby on Rails",
  "Laravel",
  ".NET Core",
  "Ktor",
  "Micronaut",
  "Hapi.js",
  "MySQL",
  "PostgreSQL",
  "Oracle",
  "SQL Server",
  "MariaDB",
  "SQLite",
  "MongoDB",
  "Redis",
  "Cassandra",
  "CouchDB",
  "DynamoDB",
  "Elasticsearch",
  "Firestore",
  "Hibernate",
  "JPA",
  "Sequelize",
  "Prisma",
  "Mongoose",
  "TypeORM",
  "Entity Framework",
  "REST",
  "GraphQL",
  "gRPC",
  "tRPC",
  "SOAP",
  "OpenAPI",
  "Swagger",
  "Postman",
  "Insomnia",
  "JWT",
  "OAuth2",
  "Passport.js",
  "Firebase Auth",
  "Keycloak",
  "Auth0",
  "Redis",
  "Memcached",
  "Ehcache",
  "RabbitMQ",
  "Kafka",
  "Amazon SQS",
  "Google Pub/Sub",
  "ActiveMQ",
  "Celery",
  "AWS Lambda",
  "Google Cloud Functions",
  "Azure Functions",
  "Firebase Functions",
  "Docker",
  "Kubernetes",
  "Docker Compose",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitLab CI",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Logstash",
  "Fluentd",
  "New Relic",
  "Sentry",
  "Helmet",
  "bcrypt",
  "CORS",
  "CSRF",
  "XSS",
  "Rate Limiting",
  "2FA",
  "SSL/TLS",
  "JUnit",
  "Mockito",
  "PyTest",
  "Mocha",
  "Chai",
  "Supertest",
  "NUnit",
  "TestNG",
  "Multer",
  "AWS S3",
  "Cloudinary",
  "Firebase Storage",
  "Nginx",
  "Apache",
  "Caddy",
  "Cron",
  "Celery",
  "Bull",
  "Agenda",
  "Quartz Scheduler",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jenkins",
  "GitLab CI/CD",
  "CircleCI",
  "Travis CI",
  "GitHub Actions",
  "Azure Pipelines",
  "TeamCity",
  "Drone CI",
  "Spinnaker",
  "Terraform",
  "Ansible",
  "Pulumi",
  "CloudFormation",
  "Chef",
  "Puppet",
  "SaltStack",
  "Docker",
  "Podman",
  "Buildah",
  "Docker Compose",
  "Kubernetes",
  "Helm",
  "OpenShift",
  "Rancher",
  "k3s",
  "EKS",
  "AKS",
  "GKE",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Logstash",
  "Kibana",
  "Fluentd",
  "Datadog",
  "New Relic",
  "Splunk",
  "Zabbix",
  "Graylog",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "IBM Cloud",
  "Oracle Cloud",
  "DigitalOcean",
  "Heroku",
  "Serverless Framework",
  "AWS SAM",
  "Chalice",
  "Azure Functions CLI",
  "Google Cloud Functions Console",
  "HashiCorp Vault",
  "SonarQube",
  "Snyk",
  "Aqua Security",
  "Anchore",
  "Trivy",
  "Falco",
  "Clair",
  "Kube-bench",
  "Nginx",
  "HAProxy",
  "Traefik",
  "Envoy",
  "Consul",
  "Istio",
  "Linkerd",
  "JFrog Artifactory",
  "Nexus Repository",
  "Harbor",
  "Quay",
  "Maven",
  "Gradle",
  "Make",
  "Bazel",
  "Ant",
  "GNU Make",
  "etcd",
  "Vault",
  "AWS Secrets Manager",
  "SSM Parameter Store",
  "Doppler",
  "GCP Secret Manager",
  "tmux",
  "ssh",
  "mosh",
  "screen",
  "Oh My Zsh",
  "zsh",
  "Bash",
  "Shell scripting",
  "PowerShell",
  "Python (for scripting, not full backend)",
  "OpenTelemetry",
  "Jaeger",
  "Zipkin",
  "Honeycomb",
  "Velero",
  "Restic",
  "BorgBackup",
  "Duplicity",
  "CloudHealth",
  "AWS Cost Explorer",
  "GCP Billing Reports",
  "Kubecost",
  "Python",
  "R",
  "Julia",
  "Scala",
  "MATLAB",
  "Pandas",
  "NumPy",
  "Polars",
  "Dask",
  "Vaex",
  "OpenRefine",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "Bokeh",
  "Altair",
  "ggplot2",
  "Dash",
  "Scikit-learn",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "Statsmodels",
  "H2O.ai",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Theano",
  "MXNet",
  "FastAI",
  "JAX",
  "SpaCy",
  "NLTK",
  "Gensim",
  "Transformers",
  "BERT",
  "GPT",
  "T5",
  "LLaMA",
  "Flair",
  "OpenCV",
  "Detectron2",
  "YOLO",
  "MediaPipe",
  "MMDetection",
  "LangChain",
  "Haystack",
  "HuggingFace",
  "OpenAI API",
  "LlamaIndex",
  "Prompt Engineering",
  "RAG (Retrieval-Augmented Generation)",
  "Apache Spark",
  "Apache Kafka",
  "Airflow",
  "dbt",
  "Snowflake",
  "Redshift",
  "BigQuery",
  "ETL Pipelines",
  "Featuretools",
  "Optuna",
  "Hyperopt",
  "Bayesian Optimization",
  "MLflow",
  "W&B (Weights & Biases)",
  "Auto-sklearn",
  "TPOT",
  "H2O AutoML",
  "Google AutoML",
  "Amazon SageMaker Autopilot",
  "ONNX",
  "TensorRT",
  "Triton Inference Server",
  "Streamlit",
  "Gradio",
  "Flask (for ML)",
  "FastAPI (for ML)",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "Elasticsearch",
  "DuckDB",
  "Parquet",
  "Feather",
  "Delta Lake",
  "Kubeflow",
  "MLflow",
  "SageMaker",
  "Azure ML Studio",
  "Tecton",
  "ZenML",
  "Neptune.ai",
  "DVC",
  "Google AI Platform",
  "Amazon SageMaker",
  "Azure Machine Learning",
  "Vertex AI",
  "Facebook Prophet",
  "ARIMA",
  "GluonTS",
  "Darts",
  "TSFresh",
  "Surprise",
  "LightFM",
  "Implicit",
  "RecBole",
  "OpenClean",
  "DataPrep",
  "Great Expectations",
  "Sweetviz",
  "Pandas-Profiling",
  "Probability Theory",
  "Linear Algebra",
  "Calculus",
  "Bayesian Inference",
  "Statistical Testing",
  "MLflow",
  "DVC",
  "Weights & Biases",
  "Comet.ml",
  "Label Studio",
  "Prodigy",
  "V7 Labs",
  "Scale.ai",
  "Reinforcement Learning",
  "Computer Vision",
  "Self-Supervised Learning",
  "Meta Learning",
  "Few-shot Learning",
  "Zero-shot Learning",
  "GANs",
  "Diffusion Models",
  "Neural Architecture Search",
  "Federated Learning",
  "Causal Inference",
  "Graph Neural Networks",
];

function extractSkills(text) {
  const foundSkills = new Set();

  for (let skill of known_skills) {
    const pattern = new RegExp(
      `\\b${skill.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`,
      "i"
    );
    if (pattern.test(text)) {
      foundSkills.add(skill);
    }
  }
  return Array.from(foundSkills);
}

module.exports = {
  extractSkills,
};
